language: node_js
notifications:
  email: false
node_js:
  - '7'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token: CODECLIMATE
after_success:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
